---
  - hosts: agent1
    become: True
    tasks:
      - name: Zainstaluj ftp
        dnf:
         name: vsftpd
         state: installed
      - name: uruchom gdy nie działa
        service:
         name: vsftpd
         state: started
