---
- hosts: mikrotik
  tasks:
  - name: Konfiguracja DHCP
    routeros_command:
      commands:
        - 'ip pool add name=zakres ranges=192.168.88.10-192.168.88.254'
        - 'ip dhcp-server add address-pool=zakres disabled=no interface=local name=lab'
        - 'ip dhcp-server network add address=192.168.88.0/24 gateway=192.168.88.1'
        - 'ip dhcp-server set lab use-radius=yes'
